# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1346, 858)
        Form.setStyleSheet("#contentTopBg{    \n"
"    background-color: #21252B;\n"
"}")
        self.contentTopBg = QtWidgets.QFrame(Form)
        self.contentTopBg.setGeometry(QtCore.QRect(0, 0, 1330, 50))
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(5, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.icon = QtWidgets.QPushButton(self.leftBox)
        self.icon.setMaximumSize(QtCore.QSize(30, 16777215))
        self.icon.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"border:none")
        self.icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/github-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon.setIcon(icon)
        self.icon.setIconSize(QtCore.QSize(28, 28))
        self.icon.setObjectName("icon")
        self.horizontalLayout_3.addWidget(self.icon)
        spacerItem1 = QtWidgets.QSpacerItem(5, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleRightInfo.setScaledContents(False)
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setStyleSheet("/* 调整按钮外边距，减小与容器的距离 */\n"
"#rightButtons .QPushButton { \n"
"    background-color: rgba(255, 255, 255, 0); \n"
"    border: none;  \n"
"    border-radius: 5px; \n"
"    margin: 0; /* 减小按钮的外边距，数值越小距离越近 */\n"
"}\n"
"\n"
"#rightButtons .QPushButton:hover { \n"
"    background-color: #2C3139; \n"
"    border-style: solid; \n"
"    border-radius: 4px; \n"
"}\n"
"\n"
"#rightButtons .QPushButton:pressed { \n"
"    background-color: #171A1E; \n"
"    border-style: solid; \n"
"    border-radius: 4px; \n"
"}\n"
"")
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_pic = QtWidgets.QPushButton(self.rightButtons)
        self.user_pic.setMinimumSize(QtCore.QSize(28, 28))
        self.user_pic.setMaximumSize(QtCore.QSize(28, 28))
        self.user_pic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user_pic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/steam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_pic.setIcon(icon1)
        self.user_pic.setIconSize(QtCore.QSize(20, 20))
        self.user_pic.setObjectName("user_pic")
        self.horizontalLayout_2.addWidget(self.user_pic)
        self.user_name = QtWidgets.QLineEdit(self.rightButtons)
        self.user_name.setMaximumSize(QtCore.QSize(50, 16777215))
        self.user_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(33, 37, 43);\n"
"border-width:0;border-style:outset")
        self.user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name.setObjectName("user_name")
        self.horizontalLayout_2.addWidget(self.user_name)
        self.settingsTopBtn = QtWidgets.QPushButton(self.rightButtons)
        self.settingsTopBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsTopBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTopBtn.setIcon(icon2)
        self.settingsTopBtn.setIconSize(QtCore.QSize(20, 20))
        self.settingsTopBtn.setObjectName("settingsTopBtn")
        self.horizontalLayout_2.addWidget(self.settingsTopBtn)
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon3)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon4)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon5)
        self.closeAppBtn.setIconSize(QtCore.QSize(18, 18))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.UnderContent = QtWidgets.QFrame(Form)
        self.UnderContent.setGeometry(QtCore.QRect(0, 50, 1331, 781))
        self.UnderContent.setStyleSheet("QFrame#sideBar{\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QFrame#content{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"")
        self.UnderContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UnderContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UnderContent.setObjectName("UnderContent")
        self.sideBar = QtWidgets.QFrame(self.UnderContent)
        self.sideBar.setGeometry(QtCore.QRect(-1, -1, 81, 781))
        self.sideBar.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    min-width: 80px;                            /* 控件最小宽度 */\n"
"    min-height: 65px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-left: 3px outset #714288;  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    background-color:rgb(92, 0, 138);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.gridLayout = QtWidgets.QGridLayout(self.sideBar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.settingUp = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.settingUp.setFont(font)
        self.settingUp.setStyleSheet("color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/aboutUs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingUp.setIcon(icon6)
        self.settingUp.setIconSize(QtCore.QSize(24, 24))
        self.settingUp.setCheckable(True)
        self.settingUp.setAutoExclusive(True)
        self.settingUp.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.settingUp.setObjectName("settingUp")
        self.gridLayout.addWidget(self.settingUp, 3, 1, 1, 1)
        self.monitor = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.monitor.setFont(font)
        self.monitor.setStyleSheet("color: rgb(255, 255, 255);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.monitor.setIcon(icon7)
        self.monitor.setIconSize(QtCore.QSize(20, 20))
        self.monitor.setCheckable(True)
        self.monitor.setAutoExclusive(True)
        self.monitor.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.monitor.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 0, 1, 1, 1)
        self.infoQuery = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.infoQuery.setFont(font)
        self.infoQuery.setStyleSheet("color: rgb(255, 255, 255);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoQuery.setIcon(icon8)
        self.infoQuery.setIconSize(QtCore.QSize(20, 20))
        self.infoQuery.setCheckable(True)
        self.infoQuery.setAutoExclusive(True)
        self.infoQuery.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.infoQuery.setObjectName("infoQuery")
        self.gridLayout.addWidget(self.infoQuery, 1, 1, 1, 1)
        self.content = QtWidgets.QFrame(self.UnderContent)
        self.content.setGeometry(QtCore.QRect(59, -1, 1271, 781))
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setGeometry(QtCore.QRect(29, -1, 1241, 771))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setStyleSheet("background-position: center;\n"
"background-image: url(:/images/images/PyDracula_1.png);\n"
"background-repeat: no-repeat;\n"
"")
        self.Home.setObjectName("Home")
        self.stackedWidget.addWidget(self.Home)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.left_content = QtWidgets.QFrame(self.page_1)
        self.left_content.setGeometry(QtCore.QRect(0, 0, 431, 781))
        self.left_content.setStyleSheet("background-color: rgb(40, 40, 60);\n"
"background-color: rgb(40, 44, 52);")
        self.left_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_content.setObjectName("left_content")
        self.left_top = QtWidgets.QFrame(self.left_content)
        self.left_top.setGeometry(QtCore.QRect(0, 0, 381, 221))
        self.left_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_top.setObjectName("left_top")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_top)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LayOut_liuliang = QtWidgets.QHBoxLayout()
        self.LayOut_liuliang.setSpacing(0)
        self.LayOut_liuliang.setObjectName("LayOut_liuliang")
        self.totalNum_2 = QtWidgets.QFrame(self.left_top)
        self.totalNum_2.setMinimumSize(QtCore.QSize(110, 0))
        self.totalNum_2.setMaximumSize(QtCore.QSize(110, 70))
        self.totalNum_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalNum_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalNum_2.setObjectName("totalNum_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.totalNum_2)
        self.gridLayout_3.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.totalNumber_2 = QtWidgets.QLineEdit(self.totalNum_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalNumber_2.sizePolicy().hasHeightForWidth())
        self.totalNumber_2.setSizePolicy(sizePolicy)
        self.totalNumber_2.setMinimumSize(QtCore.QSize(0, 30))
        self.totalNumber_2.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalNumber_2.setFont(font)
        self.totalNumber_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.totalNumber_2.setAlignment(QtCore.Qt.AlignCenter)
        self.totalNumber_2.setObjectName("totalNumber_2")
        self.gridLayout_3.addWidget(self.totalNumber_2, 1, 0, 1, 1)
        self.totalUp_2 = QtWidgets.QFrame(self.totalNum_2)
        self.totalUp_2.setMinimumSize(QtCore.QSize(100, 0))
        self.totalUp_2.setMaximumSize(QtCore.QSize(110, 20))
        self.totalUp_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalUp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalUp_2.setObjectName("totalUp_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.totalUp_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_totalUp_2 = QtWidgets.QLabel(self.totalUp_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_totalUp_2.sizePolicy().hasHeightForWidth())
        self.label_totalUp_2.setSizePolicy(sizePolicy)
        self.label_totalUp_2.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_totalUp_2.setFont(font)
        self.label_totalUp_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_totalUp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalUp_2.setObjectName("label_totalUp_2")
        self.horizontalLayout_6.addWidget(self.label_totalUp_2)
        self.lineEdit_totalUp_2 = QtWidgets.QLineEdit(self.totalUp_2)
        self.lineEdit_totalUp_2.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_totalUp_2.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_totalUp_2.setFont(font)
        self.lineEdit_totalUp_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_totalUp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_totalUp_2.setObjectName("lineEdit_totalUp_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_totalUp_2)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout_3.addWidget(self.totalUp_2, 2, 0, 1, 1)
        self.label_totalNum_2 = QtWidgets.QLabel(self.totalNum_2)
        self.label_totalNum_2.setMaximumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        self.label_totalNum_2.setFont(font)
        self.label_totalNum_2.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_totalNum_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalNum_2.setObjectName("label_totalNum_2")
        self.gridLayout_3.addWidget(self.label_totalNum_2, 0, 0, 1, 1)
        self.LayOut_liuliang.addWidget(self.totalNum_2)
        self.totalNum_3 = QtWidgets.QFrame(self.left_top)
        self.totalNum_3.setMinimumSize(QtCore.QSize(110, 0))
        self.totalNum_3.setMaximumSize(QtCore.QSize(110, 70))
        self.totalNum_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalNum_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalNum_3.setObjectName("totalNum_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.totalNum_3)
        self.gridLayout_5.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_totalNum_4 = QtWidgets.QLabel(self.totalNum_3)
        self.label_totalNum_4.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        self.label_totalNum_4.setFont(font)
        self.label_totalNum_4.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_totalNum_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalNum_4.setObjectName("label_totalNum_4")
        self.gridLayout_5.addWidget(self.label_totalNum_4, 0, 0, 1, 1)
        self.totalNumber_4 = QtWidgets.QLineEdit(self.totalNum_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalNumber_4.sizePolicy().hasHeightForWidth())
        self.totalNumber_4.setSizePolicy(sizePolicy)
        self.totalNumber_4.setMinimumSize(QtCore.QSize(0, 30))
        self.totalNumber_4.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalNumber_4.setFont(font)
        self.totalNumber_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.totalNumber_4.setAlignment(QtCore.Qt.AlignCenter)
        self.totalNumber_4.setObjectName("totalNumber_4")
        self.gridLayout_5.addWidget(self.totalNumber_4, 1, 0, 1, 1)
        self.totalUp_4 = QtWidgets.QFrame(self.totalNum_3)
        self.totalUp_4.setMinimumSize(QtCore.QSize(100, 0))
        self.totalUp_4.setMaximumSize(QtCore.QSize(110, 20))
        self.totalUp_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalUp_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalUp_4.setObjectName("totalUp_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.totalUp_4)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_totalUp_4 = QtWidgets.QLabel(self.totalUp_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_totalUp_4.sizePolicy().hasHeightForWidth())
        self.label_totalUp_4.setSizePolicy(sizePolicy)
        self.label_totalUp_4.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_totalUp_4.setFont(font)
        self.label_totalUp_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_totalUp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalUp_4.setObjectName("label_totalUp_4")
        self.horizontalLayout_13.addWidget(self.label_totalUp_4)
        self.lineEdit_totalUp_4 = QtWidgets.QLineEdit(self.totalUp_4)
        self.lineEdit_totalUp_4.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_totalUp_4.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_totalUp_4.setFont(font)
        self.lineEdit_totalUp_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_totalUp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_totalUp_4.setObjectName("lineEdit_totalUp_4")
        self.horizontalLayout_13.addWidget(self.lineEdit_totalUp_4)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.gridLayout_5.addWidget(self.totalUp_4, 2, 0, 1, 1)
        self.LayOut_liuliang.addWidget(self.totalNum_3)
        self.totalNum = QtWidgets.QFrame(self.left_top)
        self.totalNum.setMinimumSize(QtCore.QSize(110, 0))
        self.totalNum.setMaximumSize(QtCore.QSize(110, 70))
        self.totalNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalNum.setObjectName("totalNum")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.totalNum)
        self.gridLayout_2.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_totalNum = QtWidgets.QLabel(self.totalNum)
        self.label_totalNum.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        self.label_totalNum.setFont(font)
        self.label_totalNum.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_totalNum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalNum.setObjectName("label_totalNum")
        self.gridLayout_2.addWidget(self.label_totalNum, 0, 0, 1, 1)
        self.totalNumber = QtWidgets.QLineEdit(self.totalNum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalNumber.sizePolicy().hasHeightForWidth())
        self.totalNumber.setSizePolicy(sizePolicy)
        self.totalNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.totalNumber.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.totalNumber.setFont(font)
        self.totalNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.totalNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.totalNumber.setObjectName("totalNumber")
        self.gridLayout_2.addWidget(self.totalNumber, 1, 0, 1, 1)
        self.totalUp = QtWidgets.QFrame(self.totalNum)
        self.totalUp.setMinimumSize(QtCore.QSize(100, 0))
        self.totalUp.setMaximumSize(QtCore.QSize(110, 20))
        self.totalUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalUp.setObjectName("totalUp")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.totalUp)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_totalUp = QtWidgets.QLabel(self.totalUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_totalUp.sizePolicy().hasHeightForWidth())
        self.label_totalUp.setSizePolicy(sizePolicy)
        self.label_totalUp.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_totalUp.setFont(font)
        self.label_totalUp.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_totalUp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalUp.setObjectName("label_totalUp")
        self.horizontalLayout_4.addWidget(self.label_totalUp)
        self.lineEdit_totalUp = QtWidgets.QLineEdit(self.totalUp)
        self.lineEdit_totalUp.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_totalUp.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_totalUp.setFont(font)
        self.lineEdit_totalUp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_totalUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_totalUp.setObjectName("lineEdit_totalUp")
        self.horizontalLayout_4.addWidget(self.lineEdit_totalUp)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.totalUp, 2, 0, 1, 1)
        self.LayOut_liuliang.addWidget(self.totalNum)
        self.verticalLayout.addLayout(self.LayOut_liuliang)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.label_query = QtWidgets.QLabel(self.left_top)
        font = QtGui.QFont()
        font.setFamily("汉仪雅酷黑X 85W")
        font.setPointSize(12)
        font.setBold(True)
        self.label_query.setFont(font)
        self.label_query.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_query.setObjectName("label_query")
        self.verticalLayout.addWidget(self.label_query)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.rt_query_start = QtWidgets.QVBoxLayout()
        self.rt_query_start.setSpacing(0)
        self.rt_query_start.setObjectName("rt_query_start")
        self.rt_start = QtWidgets.QLabel(self.left_top)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rt_start.setFont(font)
        self.rt_start.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_start.setObjectName("rt_start")
        self.rt_query_start.addWidget(self.rt_start)
        spacerItem5 = QtWidgets.QSpacerItem(1, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_start.addItem(spacerItem5)
        self.time_start = QtWidgets.QDateTimeEdit(self.left_top)
        self.time_start.setMinimumSize(QtCore.QSize(130, 0))
        self.time_start.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time_start.setFont(font)
        self.time_start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_start.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_start.setObjectName("time_start")
        self.rt_query_start.addWidget(self.time_start)
        self.horizontalLayout_12.addLayout(self.rt_query_start)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.rt_query_end = QtWidgets.QVBoxLayout()
        self.rt_query_end.setSpacing(0)
        self.rt_query_end.setObjectName("rt_query_end")
        self.rt_end = QtWidgets.QLabel(self.left_top)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rt_end.setFont(font)
        self.rt_end.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end.setObjectName("rt_end")
        self.rt_query_end.addWidget(self.rt_end)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_end.addItem(spacerItem7)
        self.time_end = QtWidgets.QDateTimeEdit(self.left_top)
        self.time_end.setMinimumSize(QtCore.QSize(130, 0))
        self.time_end.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time_end.setFont(font)
        self.time_end.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_end.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_end.setObjectName("time_end")
        self.rt_query_end.addWidget(self.time_end)
        self.horizontalLayout_12.addLayout(self.rt_query_end)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.horizontalLayout_12.setStretch(1, 150)
        self.horizontalLayout_12.setStretch(3, 150)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.query_button = QtWidgets.QFrame(self.left_top)
        self.query_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.query_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.query_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.query_button.setObjectName("query_button")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.query_button)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.pushButton = QtWidgets.QPushButton(self.query_button)
        self.pushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.pushButton_2 = QtWidgets.QPushButton(self.query_button)
        self.pushButton_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        spacerItem11 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout.addWidget(self.query_button)
        self.center_content = QtWidgets.QFrame(self.page_1)
        self.center_content.setGeometry(QtCore.QRect(430, 0, 411, 781))
        self.center_content.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.center_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_content.setObjectName("center_content")
        self.vedio_ori = QtWidgets.QWidget(self.center_content)
        self.vedio_ori.setGeometry(QtCore.QRect(30, 70, 361, 231))
        self.vedio_ori.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_ori.setObjectName("vedio_ori")
        self.vedio_pro = QtWidgets.QWidget(self.center_content)
        self.vedio_pro.setGeometry(QtCore.QRect(30, 330, 361, 241))
        self.vedio_pro.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_pro.setObjectName("vedio_pro")
        self.widget = QtWidgets.QWidget(self.center_content)
        self.widget.setGeometry(QtCore.QRect(30, 590, 361, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(70, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/folderOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon9)
        self.pushButton_3.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/images/bofang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon10)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setStyleSheet("/*horizontal ：水平QSlider*/\n"
"QSlider::groove:horizontal {\n"
"border: 0px solid #bbb;\n"
"}\n"
"\n"
"/*1.滑动过的槽设计参数*/\n"
"QSlider::sub-page:horizontal {\n"
" /*槽颜色*/\n"
"background: rgb(90,49,255);\n"
" /*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:8px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:8px;\n"
"/*width在这里无效，不写即可*/\n"
"}\n"
"\n"
"/*2.未滑动过的槽设计参数*/\n"
"QSlider::add-page:horizontal {\n"
"/*槽颜色*/\n"
"background: rgb(255,255, 255);\n"
"/*外环大小0px就是不显示，默认也是0*/\n"
"border: 1px solid #777;\n"
"/*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:9px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:9px;\n"
"}\n"
" \n"
"/*3.平时滑动的滑块设计参数*/\n"
"QSlider::handle:horizontal {\n"
"/*滑块颜色*/\n"
"background: rgb(193,204,208);\n"
"/*滑块的宽度*/\n"
"width: 5px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(193,204,208);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 2px; \n"
" /*上遮住区域高度*/\n"
"margin-top:6px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:6px;\n"
"}\n"
"\n"
"/*4.手动拉动时显示的滑块设计参数*/\n"
"QSlider::handle:horizontal:hover {\n"
"/*滑块颜色*/\n"
"background: rgb(0, 170, 255);\n"
"/*滑块的宽度*/\n"
"width: 10px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(0, 170, 255);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 5px; \n"
" /*上遮住区域高度*/\n"
"margin-top:4px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:4px;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_8.addWidget(self.horizontalSlider)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 5)
        self.label_query_2 = QtWidgets.QLabel(self.center_content)
        self.label_query_2.setGeometry(QtCore.QRect(40, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("汉仪雅酷黑X 85W")
        font.setPointSize(12)
        font.setBold(True)
        self.label_query_2.setFont(font)
        self.label_query_2.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_query_2.setObjectName("label_query_2")
        self.right_content = QtWidgets.QFrame(self.page_1)
        self.right_content.setGeometry(QtCore.QRect(830, 0, 411, 781))
        self.right_content.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.right_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_content.setObjectName("right_content")
        self.layoutWidget = QtWidgets.QWidget(self.right_content)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 180, 351, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.right_under = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.right_under.setContentsMargins(0, 0, 0, 0)
        self.right_under.setObjectName("right_under")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.label_vio_rt = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("汉仪雅酷黑X 85W")
        font.setPointSize(12)
        font.setBold(True)
        self.label_vio_rt.setFont(font)
        self.label_vio_rt.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_vio_rt.setObjectName("label_vio_rt")
        self.horizontalLayout_7.addWidget(self.label_vio_rt)
        self.right_under.addLayout(self.horizontalLayout_7)
        self.scrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 520))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {/*设置滚动条背景*/\n"
"    border: none;\n"
"    border-radius:5px;\n"
"    width: 10px;\n"
"    background:rgba(153, 153, 153, 0.5);\n"
"}\n"
"QScrollBar::handle:vertical {/*设置滑动条*/\n"
"    border: none;\n"
"    border-radius:5px; \n"
"    background-color: rgb(55, 156, 212);\n"
"  }\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      height: 0px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      height: 0px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"  QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border:none;\n"
"      width: 0px;\n"
"      height: 0px;\n"
"  }\n"
"  QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
" \n"
" \n"
" \n"
" \n"
"QScrollBar:horizontal {/*设置滚动条背景*/\n"
"    border: none;\n"
"    border-radius:2px;\n"
"    height: 20px;\n"
"    background:rgba(153, 153, 153, 0.5);\n"
"    border-image: url(:/icon/tou.png);\n"
"}\n"
"QScrollBar::handle:horizontal {/*设置滑动条*/\n"
"    border: none;\n"
"    border-radius:2px; \n"
" \n"
"    background-color: rgb(55, 156, 212);\n"
"  }\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: none;\n"
"      width: 0px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"QScrollBar::add-line:horizontal {\n"
"      border: none;\n"
"      width: 0px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"  QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:vertical {\n"
"    border:none;\n"
"      width: 0px;\n"
"      height: 0px;\n"
"  }\n"
"  QScrollBar::add-page:horizontal, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
" \n"
" \n"
" \n"
" \n"
" ")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 1018))
        self.scrollAreaWidgetContents.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(200, 1000))
        self.plainTextEdit.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_11.addWidget(self.plainTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.right_under.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.top_bar = QtWidgets.QFrame(self.page_2)
        self.top_bar.setGeometry(QtCore.QRect(0, 0, 1241, 51))
        self.top_bar.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 120px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-bottom: 3px outset rgb(170, 99, 204);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    background-color:rgb(92, 0, 138);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.violations = QtWidgets.QToolButton(self.top_bar)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.violations.setFont(font)
        self.violations.setStyleSheet("color: rgb(255, 255, 255);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/images/violations.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.violations.setIcon(icon11)
        self.violations.setIconSize(QtCore.QSize(24, 24))
        self.violations.setCheckable(True)
        self.violations.setAutoExclusive(True)
        self.violations.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.violations.setObjectName("violations")
        self.horizontalLayout_10.addWidget(self.violations)
        self.flow = QtWidgets.QToolButton(self.top_bar)
        self.flow.setStyleSheet("color: rgb(255, 255, 255);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/images/flow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flow.setIcon(icon12)
        self.flow.setIconSize(QtCore.QSize(18, 18))
        self.flow.setCheckable(True)
        self.flow.setAutoExclusive(True)
        self.flow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.flow.setObjectName("flow")
        self.horizontalLayout_10.addWidget(self.flow)
        self.blank = QtWidgets.QToolButton(self.top_bar)
        self.blank.setMinimumSize(QtCore.QSize(1006, 46))
        self.blank.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 1000px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"r")
        self.blank.setText("")
        self.blank.setObjectName("blank")
        self.horizontalLayout_10.addWidget(self.blank)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 50, 1241, 721))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.home_sub = QtWidgets.QWidget()
        self.home_sub.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.home_sub.setObjectName("home_sub")
        self.frame = QtWidgets.QFrame(self.home_sub)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1241, 721))
        self.frame.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_query_4 = QtWidgets.QLabel(self.frame)
        self.label_query_4.setGeometry(QtCore.QRect(440, 200, 421, 151))
        self.label_query_4.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("汉仪雅酷黑X 85W")
        font.setPointSize(36)
        font.setBold(True)
        self.label_query_4.setFont(font)
        self.label_query_4.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_query_4.setObjectName("label_query_4")
        self.stackedWidget_2.addWidget(self.home_sub)
        self.info_query = QtWidgets.QWidget()
        self.info_query.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.info_query.setObjectName("info_query")
        self.frame_query = QtWidgets.QFrame(self.info_query)
        self.frame_query.setGeometry(QtCore.QRect(0, 0, 800, 721))
        self.frame_query.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_query.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_query.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_query.setObjectName("frame_query")
        self.violation_query = QtWidgets.QFrame(self.frame_query)
        self.violation_query.setGeometry(QtCore.QRect(10, 20, 700, 103))
        self.violation_query.setMaximumSize(QtCore.QSize(700, 16777215))
        self.violation_query.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.violation_query.setFrameShadow(QtWidgets.QFrame.Raised)
        self.violation_query.setObjectName("violation_query")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.violation_query)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_car_num = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_car_num.setFont(font)
        self.label_car_num.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_car_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_car_num.setObjectName("label_car_num")
        self.horizontalLayout_5.addWidget(self.label_car_num)
        self.lineEdit_violation = QtWidgets.QLineEdit(self.violation_query)
        self.lineEdit_violation.setMinimumSize(QtCore.QSize(130, 30))
        self.lineEdit_violation.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_violation.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}")
        self.lineEdit_violation.setObjectName("lineEdit_violation")
        self.horizontalLayout_5.addWidget(self.lineEdit_violation)
        spacerItem13 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.label_violation = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_violation.setFont(font)
        self.label_violation.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_violation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_violation.setObjectName("label_violation")
        self.horizontalLayout_5.addWidget(self.label_violation)
        self.comboBox_violation = QtWidgets.QComboBox(self.violation_query)
        self.comboBox_violation.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox_violation.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.comboBox_violation.setFont(font)
        self.comboBox_violation.setAutoFillBackground(False)
        self.comboBox_violation.setStyleSheet("QComboBox{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: #404758;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/icons/cil-arrow-bottom.png); /* 自定义箭头图标 */\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(170, 99, 204);    \n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 10px;\n"
"    selection-background-color: #6272a4;\n"
"}")
        self.comboBox_violation.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_violation.setFrame(True)
        self.comboBox_violation.setObjectName("comboBox_violation")
        self.comboBox_violation.addItem("")
        self.comboBox_violation.addItem("")
        self.comboBox_violation.addItem("")
        self.comboBox_violation.addItem("")
        self.comboBox_violation.addItem("")
        self.comboBox_violation.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_violation)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rt_query_end_2 = QtWidgets.QVBoxLayout()
        self.rt_query_end_2.setSpacing(0)
        self.rt_query_end_2.setObjectName("rt_query_end_2")
        self.rt_end_2 = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rt_end_2.setFont(font)
        self.rt_end_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end_2.setObjectName("rt_end_2")
        self.rt_query_end_2.addWidget(self.rt_end_2)
        spacerItem15 = QtWidgets.QSpacerItem(1, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_end_2.addItem(spacerItem15)
        self.time_end_2 = QtWidgets.QDateTimeEdit(self.violation_query)
        self.time_end_2.setMinimumSize(QtCore.QSize(150, 0))
        self.time_end_2.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.time_end_2.setFont(font)
        self.time_end_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_end_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_end_2.setObjectName("time_end_2")
        self.rt_query_end_2.addWidget(self.time_end_2)
        self.horizontalLayout_14.addLayout(self.rt_query_end_2)
        spacerItem16 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.rt_query_end_3 = QtWidgets.QVBoxLayout()
        self.rt_query_end_3.setSpacing(0)
        self.rt_query_end_3.setObjectName("rt_query_end_3")
        self.rt_end_3 = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rt_end_3.setFont(font)
        self.rt_end_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end_3.setObjectName("rt_end_3")
        self.rt_query_end_3.addWidget(self.rt_end_3)
        spacerItem17 = QtWidgets.QSpacerItem(1, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_end_3.addItem(spacerItem17)
        self.time_end_3 = QtWidgets.QDateTimeEdit(self.violation_query)
        self.time_end_3.setMinimumSize(QtCore.QSize(150, 0))
        self.time_end_3.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.time_end_3.setFont(font)
        self.time_end_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_end_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_end_3.setObjectName("time_end_3")
        self.rt_query_end_3.addWidget(self.time_end_3)
        self.horizontalLayout_14.addLayout(self.rt_query_end_3)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.pBtn_vio_query = QtWidgets.QPushButton(self.violation_query)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_vio_query.sizePolicy().hasHeightForWidth())
        self.pBtn_vio_query.setSizePolicy(sizePolicy)
        self.pBtn_vio_query.setMinimumSize(QtCore.QSize(80, 30))
        self.pBtn_vio_query.setMaximumSize(QtCore.QSize(63, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pBtn_vio_query.setFont(font)
        self.pBtn_vio_query.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/images/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtn_vio_query.setIcon(icon13)
        self.pBtn_vio_query.setObjectName("pBtn_vio_query")
        self.horizontalLayout_15.addWidget(self.pBtn_vio_query)
        self.output_vio = QtWidgets.QPushButton(self.violation_query)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_vio.sizePolicy().hasHeightForWidth())
        self.output_vio.setSizePolicy(sizePolicy)
        self.output_vio.setMinimumSize(QtCore.QSize(100, 30))
        self.output_vio.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_vio.setFont(font)
        self.output_vio.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/images/output_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.output_vio.setIcon(icon14)
        self.output_vio.setObjectName("output_vio")
        self.horizontalLayout_15.addWidget(self.output_vio)
        self.frame_statistics = QtWidgets.QFrame(self.info_query)
        self.frame_statistics.setGeometry(QtCore.QRect(805, 0, 441, 721))
        self.frame_statistics.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_statistics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_statistics.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_statistics.setObjectName("frame_statistics")
        self.pBtn_vio_statistics = QtWidgets.QPushButton(self.frame_statistics)
        self.pBtn_vio_statistics.setGeometry(QtCore.QRect(30, 20, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_vio_statistics.sizePolicy().hasHeightForWidth())
        self.pBtn_vio_statistics.setSizePolicy(sizePolicy)
        self.pBtn_vio_statistics.setMinimumSize(QtCore.QSize(150, 30))
        self.pBtn_vio_statistics.setMaximumSize(QtCore.QSize(200, 30))
        self.pBtn_vio_statistics.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/images/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtn_vio_statistics.setIcon(icon15)
        self.pBtn_vio_statistics.setObjectName("pBtn_vio_statistics")
        self.widget_vio_statistics = QtWidgets.QWidget(self.frame_statistics)
        self.widget_vio_statistics.setGeometry(QtCore.QRect(20, 70, 391, 631))
        self.widget_vio_statistics.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"border-top-right-radius: 8px;         /* 右上角圆角 */\n"
"border-top-left-radius: 8px;        \n"
"border-bottom-right-radius: 8px;      /* 右下角圆角 */\n"
"border-bottom-left-radius: 8px;         /* 右上角圆角 */")
        self.widget_vio_statistics.setObjectName("widget_vio_statistics")
        self.stackedWidget_2.addWidget(self.info_query)
        self.info_query_flow = QtWidgets.QWidget()
        self.info_query_flow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.info_query_flow.setObjectName("info_query_flow")
        self.frame_query_flow = QtWidgets.QFrame(self.info_query_flow)
        self.frame_query_flow.setGeometry(QtCore.QRect(0, 0, 800, 721))
        self.frame_query_flow.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_query_flow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_query_flow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_query_flow.setObjectName("frame_query_flow")
        self.label_query_flow = QtWidgets.QLabel(self.frame_query_flow)
        self.label_query_flow.setGeometry(QtCore.QRect(50, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("汉仪雅酷黑X 85W")
        font.setPointSize(12)
        font.setBold(True)
        self.label_query_flow.setFont(font)
        self.label_query_flow.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_query_flow.setObjectName("label_query_flow")
        self.frame_statistics_flow = QtWidgets.QFrame(self.info_query_flow)
        self.frame_statistics_flow.setGeometry(QtCore.QRect(805, 0, 521, 721))
        self.frame_statistics_flow.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_statistics_flow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_statistics_flow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_statistics_flow.setObjectName("frame_statistics_flow")
        self.widget_flow_statistics = QtWidgets.QWidget(self.frame_statistics_flow)
        self.widget_flow_statistics.setGeometry(QtCore.QRect(20, 70, 391, 601))
        self.widget_flow_statistics.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"border-top-right-radius: 8px;         /* 右上角圆角 */\n"
"border-top-left-radius: 8px;        \n"
"border-bottom-right-radius: 8px;      /* 右下角圆角 */\n"
"border-bottom-left-radius: 8px;         /* 右上角圆角 */")
        self.widget_flow_statistics.setObjectName("widget_flow_statistics")
        self.pBtn_flow_statistics = QtWidgets.QPushButton(self.frame_statistics_flow)
        self.pBtn_flow_statistics.setGeometry(QtCore.QRect(30, 20, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_flow_statistics.sizePolicy().hasHeightForWidth())
        self.pBtn_flow_statistics.setSizePolicy(sizePolicy)
        self.pBtn_flow_statistics.setMinimumSize(QtCore.QSize(150, 30))
        self.pBtn_flow_statistics.setMaximumSize(QtCore.QSize(200, 30))
        self.pBtn_flow_statistics.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.pBtn_flow_statistics.setIcon(icon15)
        self.pBtn_flow_statistics.setObjectName("pBtn_flow_statistics")
        self.stackedWidget_2.addWidget(self.info_query_flow)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.content.raise_()
        self.sideBar.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleRightInfo.setText(_translate("Form", "Intelligent Traffic Management Systems"))
        self.user_pic.setToolTip(_translate("Form", "Settings"))
        self.user_name.setText(_translate("Form", "用户名"))
        self.settingsTopBtn.setToolTip(_translate("Form", "Settings"))
        self.minimizeAppBtn.setToolTip(_translate("Form", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("Form", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("Form", "Close"))
        self.settingUp.setText(_translate("Form", "关于我们"))
        self.monitor.setText(_translate("Form", "实时监控"))
        self.infoQuery.setText(_translate("Form", "信息查询"))
        self.totalNumber_2.setText(_translate("Form", "---"))
        self.label_totalUp_2.setText(_translate("Form", "同比增长"))
        self.lineEdit_totalUp_2.setText(_translate("Form", "^00.0%"))
        self.label_totalNum_2.setText(_translate("Form", " 现车流总数"))
        self.label_totalNum_4.setText(_translate("Form", "驶入总数"))
        self.totalNumber_4.setText(_translate("Form", "---"))
        self.label_totalUp_4.setText(_translate("Form", "同比增长"))
        self.lineEdit_totalUp_4.setText(_translate("Form", "^00.0%"))
        self.label_totalNum.setText(_translate("Form", "驶出总数"))
        self.totalNumber.setText(_translate("Form", "---"))
        self.label_totalUp.setText(_translate("Form", "同比增长"))
        self.lineEdit_totalUp.setText(_translate("Form", "^00.0%"))
        self.label_query.setText(_translate("Form", "   车辆搜索记录"))
        self.rt_start.setText(_translate("Form", "起始时间："))
        self.rt_end.setText(_translate("Form", "终止时间："))
        self.pushButton.setText(_translate("Form", "重置"))
        self.pushButton_2.setText(_translate("Form", "搜索"))
        self.pushButton_3.setText(_translate("Form", "打开"))
        self.label_query_2.setText(_translate("Form", "视频监控"))
        self.label_vio_rt.setText(_translate("Form", "违规信息"))
        self.violations.setText(_translate("Form", "违规查询"))
        self.flow.setText(_translate("Form", " 流量查询"))
        self.label_query_4.setText(_translate("Form", "这是信息查询页面"))
        self.label_car_num.setText(_translate("Form", "车牌号"))
        self.label_violation.setText(_translate("Form", "违规类别"))
        self.comboBox_violation.setItemText(0, _translate("Form", "闯红灯"))
        self.comboBox_violation.setItemText(1, _translate("Form", "不按车道行驶"))
        self.comboBox_violation.setItemText(2, _translate("Form", "违章变道"))
        self.comboBox_violation.setItemText(3, _translate("Form", "逆行"))
        self.comboBox_violation.setItemText(4, _translate("Form", "压(实)线"))
        self.comboBox_violation.setItemText(5, _translate("Form", "超速"))
        self.rt_end_2.setText(_translate("Form", "终止时间："))
        self.rt_end_3.setText(_translate("Form", "开始时间："))
        self.pBtn_vio_query.setText(_translate("Form", "查询"))
        self.output_vio.setText(_translate("Form", "导出数据"))
        self.pBtn_vio_statistics.setText(_translate("Form", "违规数据分析"))
        self.label_query_flow.setText(_translate("Form", "历史数据"))
        self.pBtn_flow_statistics.setText(_translate("Form", "流量数据分析"))
