# enhanced_stats.py
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1136, 648)
        Form.setStyleSheet("#contentTopBg{    \n"
"    background-color: #21252B;\n"
"}")
        self.contentTopBg = QtWidgets.QFrame(Form)
        self.contentTopBg.setGeometry(QtCore.QRect(0, 0, 1081, 50))
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(5, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/icons/github-fill.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(5, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleRightInfo.setScaledContents(False)
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setStyleSheet("/* 调整按钮外边距，减小与容器的距离 */\n"
"#rightButtons .QPushButton { \n"
"    background-color: rgba(255, 255, 255, 0); \n"
"    border: none;  \n"
"    border-radius: 5px; \n"
"    margin: 0; /* 减小按钮的外边距，数值越小距离越近 */\n"
"}\n"
"\n"
"#rightButtons .QPushButton:hover { \n"
"    background-color: #2C3139; \n"
"    border-style: solid; \n"
"    border-radius: 4px; \n"
"}\n"
"\n"
"#rightButtons .QPushButton:pressed { \n"
"    background-color: #171A1E; \n"
"    border-style: solid; \n"
"    border-radius: 4px; \n"
"}\n"
"")
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settingsTopBtn_2 = QtWidgets.QPushButton(self.rightButtons)
        self.settingsTopBtn_2.setMinimumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn_2.setMaximumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsTopBtn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/steam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTopBtn_2.setIcon(icon)
        self.settingsTopBtn_2.setIconSize(QtCore.QSize(20, 20))
        self.settingsTopBtn_2.setObjectName("settingsTopBtn_2")
        self.horizontalLayout_2.addWidget(self.settingsTopBtn_2)
        self.lineEdit = QtWidgets.QLineEdit(self.rightButtons)
        self.lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(33, 37, 43);\n"
"border-width:0;border-style:outset")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.settingsTopBtn = QtWidgets.QPushButton(self.rightButtons)
        self.settingsTopBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsTopBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTopBtn.setIcon(icon1)
        self.settingsTopBtn.setIconSize(QtCore.QSize(20, 20))
        self.settingsTopBtn.setObjectName("settingsTopBtn")
        self.horizontalLayout_2.addWidget(self.settingsTopBtn)
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon2)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon3)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon4)
        self.closeAppBtn.setIconSize(QtCore.QSize(18, 18))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.UnderContent = QtWidgets.QFrame(Form)
        self.UnderContent.setGeometry(QtCore.QRect(0, 50, 1081, 541))
        self.UnderContent.setStyleSheet("QFrame#sideBar{\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QFrame#content{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"")
        self.UnderContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UnderContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UnderContent.setObjectName("UnderContent")
        self.sideBar = QtWidgets.QFrame(self.UnderContent)
        self.sideBar.setGeometry(QtCore.QRect(-1, -1, 75, 541))
        self.sideBar.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    min-width: 75px;                            /* 控件最小宽度 */\n"
"    min-height: 60px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-left: 3px outset #714288;  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    background-color:rgb(92, 0, 138);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.gridLayout = QtWidgets.QGridLayout(self.sideBar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.settingUp = QtWidgets.QToolButton(self.sideBar)
        self.settingUp.setStyleSheet("color: rgb(255, 255, 255);")
        self.settingUp.setIcon(icon1)
        self.settingUp.setIconSize(QtCore.QSize(20, 20))
        self.settingUp.setCheckable(True)
        self.settingUp.setAutoExclusive(True)
        self.settingUp.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.settingUp.setObjectName("settingUp")
        self.gridLayout.addWidget(self.settingUp, 3, 1, 1, 1)
        self.monitor = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.monitor.setFont(font)
        self.monitor.setStyleSheet("color: rgb(255, 255, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.monitor.setIcon(icon5)
        self.monitor.setIconSize(QtCore.QSize(20, 20))
        self.monitor.setCheckable(True)
        self.monitor.setAutoExclusive(True)
        self.monitor.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.monitor.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 0, 1, 1, 1)
        self.infoQuery = QtWidgets.QToolButton(self.sideBar)
        self.infoQuery.setStyleSheet("color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoQuery.setIcon(icon6)
        self.infoQuery.setIconSize(QtCore.QSize(20, 20))
        self.infoQuery.setCheckable(True)
        self.infoQuery.setAutoExclusive(True)
        self.infoQuery.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.infoQuery.setObjectName("infoQuery")
        self.gridLayout.addWidget(self.infoQuery, 1, 1, 1, 1)
        self.content = QtWidgets.QFrame(self.UnderContent)
        self.content.setGeometry(QtCore.QRect(59, -1, 1035, 541))
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setGeometry(QtCore.QRect(39, 9, 971, 511))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setStyleSheet("background-position: center;\n"
"background-image: url(:/images/images/PyDracula_vertical.png);\n"
"background-repeat: no-repeat;\n"
"")
        self.Home.setObjectName("Home")
        self.stackedWidget.addWidget(self.Home)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        
        # 修改为垂直布局的left_content
        self.left_content = QtWidgets.QFrame(self.page_1)
        self.left_content.setGeometry(QtCore.QRect(0, 0, 291, 511))
        self.left_content.setStyleSheet("background-color: rgb(40, 40, 60);\n"
"background-color: rgb(40, 44, 52);")
        self.left_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_content.setObjectName("left_content")
        
        # 创建垂直布局
        self.left_content_layout = QtWidgets.QVBoxLayout(self.left_content)
        self.left_content_layout.setContentsMargins(10, 10, 10, 10)
        self.left_content_layout.setSpacing(10)
        self.left_content_layout.setObjectName("left_content_layout")
        
        # 顶部统计信息区域
        self.widget = QtWidgets.QWidget(self.left_content)
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("background-color: transparent;")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        
        # 现车流总数
        self.totalNum = QtWidgets.QFrame(self.widget)
        self.totalNum.setMaximumSize(QtCore.QSize(90, 60))
        self.totalNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalNum.setObjectName("totalNum")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.totalNum)
        self.gridLayout_2.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_totalNum = QtWidgets.QLabel(self.totalNum)
        self.label_totalNum.setMaximumSize(QtCore.QSize(90, 20))
        self.label_totalNum.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_totalNum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalNum.setObjectName("label_totalNum")
        self.gridLayout_2.addWidget(self.label_totalNum, 0, 0, 1, 1)
        self.totalNumber = QtWidgets.QLineEdit(self.totalNum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalNumber.sizePolicy().hasHeightForWidth())
        self.totalNumber.setSizePolicy(sizePolicy)
        self.totalNumber.setMaximumSize(QtCore.QSize(90, 20))
        self.totalNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.totalNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.totalNumber.setObjectName("totalNumber")
        self.gridLayout_2.addWidget(self.totalNumber, 1, 0, 1, 1)
        self.totalUp = QtWidgets.QFrame(self.totalNum)
        self.totalUp.setMaximumSize(QtCore.QSize(90, 20))
        self.totalUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalUp.setObjectName("totalUp")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.totalUp)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_totalUp = QtWidgets.QLabel(self.totalUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_totalUp.sizePolicy().hasHeightForWidth())
        self.label_totalUp.setSizePolicy(sizePolicy)
        self.label_totalUp.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_totalUp.setFont(font)
        self.label_totalUp.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_totalUp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalUp.setObjectName("label_totalUp")
        self.horizontalLayout_4.addWidget(self.label_totalUp)
        self.lineEdit_totalUp = QtWidgets.QLineEdit(self.totalUp)
        self.lineEdit_totalUp.setMinimumSize(QtCore.QSize(1, 0))
        self.lineEdit_totalUp.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lineEdit_totalUp.setFont(font)
        self.lineEdit_totalUp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_totalUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_totalUp.setObjectName("lineEdit_totalUp")
        self.horizontalLayout_4.addWidget(self.lineEdit_totalUp)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.totalUp, 2, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.totalNum)
        
        # 驶入车流数
        self.inNum = QtWidgets.QFrame(self.widget)
        self.inNum.setMaximumSize(QtCore.QSize(90, 60))
        self.inNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inNum.setObjectName("inNum")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.inNum)
        self.gridLayout_4.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_inNum = QtWidgets.QLabel(self.inNum)
        self.label_inNum.setMaximumSize(QtCore.QSize(90, 20))
        self.label_inNum.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_inNum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inNum.setObjectName("label_inNum")
        self.gridLayout_4.addWidget(self.label_inNum, 0, 0, 1, 1)
        self.inNumber = QtWidgets.QLineEdit(self.inNum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inNumber.sizePolicy().hasHeightForWidth())
        self.inNumber.setSizePolicy(sizePolicy)
        self.inNumber.setMaximumSize(QtCore.QSize(90, 20))
        self.inNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.inNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.inNumber.setObjectName("inNumber")
        self.gridLayout_4.addWidget(self.inNumber, 1, 0, 1, 1)
        self.inUp = QtWidgets.QFrame(self.inNum)
        self.inUp.setMaximumSize(QtCore.QSize(90, 20))
        self.inUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inUp.setObjectName("inUp")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.inUp)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_inUp = QtWidgets.QLabel(self.inUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_inUp.sizePolicy().hasHeightForWidth())
        self.label_inUp.setSizePolicy(sizePolicy)
        self.label_inUp.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_inUp.setFont(font)
        self.label_inUp.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_inUp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inUp.setObjectName("label_inUp")
        self.horizontalLayout_6.addWidget(self.label_inUp)
        self.lineEdit_inUp = QtWidgets.QLineEdit(self.inUp)
        self.lineEdit_inUp.setMinimumSize(QtCore.QSize(1, 0))
        self.lineEdit_inUp.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lineEdit_inUp.setFont(font)
        self.lineEdit_inUp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_inUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_inUp.setObjectName("lineEdit_inUp")
        self.horizontalLayout_6.addWidget(self.lineEdit_inUp)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout_4.addWidget(self.inUp, 2, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.inNum)
        
        # 驶出车流数
        self.totalNum_3 = QtWidgets.QFrame(self.widget)
        self.totalNum_3.setMaximumSize(QtCore.QSize(90, 60))
        self.totalNum_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalNum_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalNum_3.setObjectName("totalNum_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.totalNum_3)
        self.gridLayout_5.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_totalNum_4 = QtWidgets.QLabel(self.totalNum_3)
        self.label_totalNum_4.setMaximumSize(QtCore.QSize(90, 20))
        self.label_totalNum_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_totalNum_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalNum_4.setObjectName("label_totalNum_4")
        self.gridLayout_5.addWidget(self.label_totalNum_4, 0, 0, 1, 1)
        self.tatalNumber_4 = QtWidgets.QLineEdit(self.totalNum_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tatalNumber_4.sizePolicy().hasHeightForWidth())
        self.tatalNumber_4.setSizePolicy(sizePolicy)
        self.tatalNumber_4.setMaximumSize(QtCore.QSize(90, 20))
        self.tatalNumber_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.tatalNumber_4.setAlignment(QtCore.Qt.AlignCenter)
        self.tatalNumber_4.setObjectName("tatalNumber_4")
        self.gridLayout_5.addWidget(self.tatalNumber_4, 1, 0, 1, 1)
        self.totalUp_4 = QtWidgets.QFrame(self.totalNum_3)
        self.totalUp_4.setMaximumSize(QtCore.QSize(90, 20))
        self.totalUp_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalUp_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalUp_4.setObjectName("totalUp_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.totalUp_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.totalUp_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.totalUp_4)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(1, 0))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.gridLayout_5.addWidget(self.totalUp_4, 2, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.totalNum_3)
        self.left_content_layout.addWidget(self.widget)
        
        # 车辆搜索记录标签
        self.label_query = QtWidgets.QLabel(self.left_content)
        font = QtGui.QFont()
        font.setFamily("汉仪雅酷黑X 85W")
        font.setPointSize(12)
        font.setBold(True)
        self.label_query.setFont(font)
        self.label_query.setStyleSheet("color: rgb(0, 170, 255);\n"
"margin-top: 10px;")
        self.label_query.setObjectName("label_query")
        self.left_content_layout.addWidget(self.label_query)
        
        # 时间选择区域
        self.widget1 = QtWidgets.QWidget(self.left_content)
        self.widget1.setObjectName("widget1")
        self.rt_query = QtWidgets.QHBoxLayout(self.widget1)
        self.rt_query.setContentsMargins(0, 5, 0, 0)
        self.rt_query.setObjectName("rt_query")
        self.rt_query_start = QtWidgets.QVBoxLayout()
        self.rt_query_start.setObjectName("rt_query_start")
        self.rt_start = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rt_start.setFont(font)
        self.rt_start.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_start.setObjectName("rt_start")
        self.rt_query_start.addWidget(self.rt_start)
        self.time_start = QtWidgets.QDateTimeEdit(self.widget1)
        self.time_start.setMinimumSize(QtCore.QSize(110, 0))
        self.time_start.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time_start.setFont(font)
        self.time_start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_start.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_start.setObjectName("time_start")
        self.rt_query_start.addWidget(self.time_start)
        self.rt_query.addLayout(self.rt_query_start)
        spacerItem3 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.rt_query.addItem(spacerItem3)
        self.rt_query_end = QtWidgets.QVBoxLayout()
        self.rt_query_end.setSpacing(0)
        self.rt_query_end.setObjectName("rt_query_end")
        self.rt_end = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rt_end.setFont(font)
        self.rt_end.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end.setObjectName("rt_end")
        self.rt_query_end.addWidget(self.rt_end)
        self.time_end = QtWidgets.QDateTimeEdit(self.widget1)
        self.time_end.setMinimumSize(QtCore.QSize(110, 0))
        self.time_end.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time_end.setFont(font)
        self.time_end.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_end.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_end.setObjectName("time_end")
        self.rt_query_end.addWidget(self.time_end)
        self.rt_query.addLayout(self.rt_query_end)
        self.left_content_layout.addWidget(self.widget1)
        
        # 搜索按钮区域
        self.query_button = QtWidgets.QFrame(self.left_content)
        self.query_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.query_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.query_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.query_button.setObjectName("query_button")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.query_button)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton = QtWidgets.QPushButton(self.query_button)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.query_button)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.left_content_layout.addWidget(self.query_button)
        
        # 新增表格区域
        self.tableWidget = QtWidgets.QTableWidget(self.left_content)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setStyleSheet("background-color: rgb(30, 30, 40);\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "gridline-color: rgb(60, 60, 70);\n"
                                       "selection-background-color: rgb(0, 170, 255);\n"
                                       "selection-color: rgb(255, 255, 255);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(5)
        
        # 设置表头
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        
        # 设置表格内容
        for i in range(10):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 4, item)
        
        # 设置表头样式
        header = self.tableWidget.horizontalHeader()
        header.setStyleSheet("background-color: rgb(50, 50, 60);\n"
                             "color: rgb(255, 255, 255);\n"
                             "font-weight: bold;")
        header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        
        self.left_content_layout.addWidget(self.tableWidget)
        self.left_content_layout.addStretch()
        
        # 右侧内容区域
        self.center_content = QtWidgets.QFrame(self.page_1)
        self.center_content.setGeometry(QtCore.QRect(320, 0, 371, 511))
        self.center_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_content.setObjectName("center_content")
        self.right_content = QtWidgets.QFrame(self.page_1)
        self.right_content.setGeometry(QtCore.QRect(709, -1, 261, 511))
        self.right_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_content.setObjectName("right_content")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(210, 250, 54, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(170, 170, 54, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_3)
        self.content.raise_()
        self.sideBar.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleRightInfo.setText(_translate("Form", "Intelligent Traffic Management Systems"))
        self.settingsTopBtn_2.setToolTip(_translate("Form", "Settings"))
        self.lineEdit.setText(_translate("Form", "用户名"))
        self.settingsTopBtn.setToolTip(_translate("Form", "Settings"))
        self.minimizeAppBtn.setToolTip(_translate("Form", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("Form", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("Form", "Close"))
        self.settingUp.setText(_translate("Form", "设置"))
        self.monitor.setText(_translate("Form", "实时监控"))
        self.infoQuery.setText(_translate("Form", "信息查询"))
        self.label_totalNum.setText(_translate("Form", "现车流总数"))
        self.totalNumber.setText(_translate("Form", "---"))
        self.label_totalUp.setText(_translate("Form", "同比增长"))
        self.lineEdit_totalUp.setText(_translate("Form", "^00.0%"))
        self.label_inNum.setText(_translate("Form", "驶入车流数"))
        self.inNumber.setText(_translate("Form", "---"))
        self.label_inUp.setText(_translate("Form", "同比增长"))
        self.lineEdit_inUp.setText(_translate("Form", "^00.0%"))
        self.label_totalNum_4.setText(_translate("Form", "驶出车流数"))
        self.tatalNumber_4.setText(_translate("Form", "---"))
        self.label_8.setText(_translate("Form", "同比增长"))
        self.lineEdit_6.setText(_translate("Form", "^00.0%"))
        self.label_query.setText(_translate("Form", "车辆搜索记录"))
        self.rt_start.setText(_translate("Form", "起始时间："))
        self.rt_end.setText(_translate("Form", "终止时间："))
        self.pushButton.setText(_translate("Form", "重置"))
        self.pushButton_2.setText(_translate("Form", "搜索"))
        
        # 表格表头
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "车牌号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "进入时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "离开时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "停留时长"))
        
        # 表格内容示例
        for i in range(10):
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("Form", str(i+1)))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("Form", f"京A{12345+i:05d}"))
            item = self.tableWidget.item(i, 2)
            item.setText(_translate("Form", f"08:{10+i:02d}:00"))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("Form", f"09:{20+i:02d}:00"))
            item = self.tableWidget.item(i, 4)
            item.setText(_translate("Form", f"{10+i}分钟"))
        
        self.label_3.setText(_translate("Form", "page2"))
        self.label_4.setText(_translate("Form", "page3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
