# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views\stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2040, 1281)
        Form.setStyleSheet("#contentTopBg{    \n"
"    background-color: #21252B;\n"
"}")
        self.contentTopBg = QtWidgets.QFrame(Form)
        self.contentTopBg.setGeometry(QtCore.QRect(0, 0, 2040, 90))
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 90))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 70))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(5, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.icon = QtWidgets.QPushButton(self.leftBox)
        self.icon.setMinimumSize(QtCore.QSize(110, 70))
        self.icon.setMaximumSize(QtCore.QSize(110, 16777215))
        self.icon.setStyleSheet("background-color:#21252B;\n"
"border:none")
        self.icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/logo1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon.setIcon(icon)
        self.icon.setIconSize(QtCore.QSize(60, 60))
        self.icon.setObjectName("icon")
        self.horizontalLayout_3.addWidget(self.icon)
        spacerItem1 = QtWidgets.QSpacerItem(5, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleRightInfo.setScaledContents(False)
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(200, 28))
        self.rightButtons.setMaximumSize(QtCore.QSize(350, 16777215))
        self.rightButtons.setStyleSheet("/* 调整按钮外边距，减小与容器的距离 */\n"
"#rightButtons .QPushButton { \n"
"    background-color: rgba(255, 255, 255, 0); \n"
"    border: none;  \n"
"    border-radius: 5px; \n"
"    margin: 0; /* 减小按钮的外边距，数值越小距离越近 */\n"
"}\n"
"\n"
"#rightButtons .QPushButton:hover { \n"
"    background-color: rgb(120, 120, 120); \n"
"    border-style: solid; \n"
"    border-radius: 4px; \n"
"}\n"
"\n"
"#rightButtons .QPushButton:pressed { \n"
"    background-color: #171A1E; \n"
"    border-style: solid; \n"
"    border-radius: 4px; \n"
"}\n"
"")
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_name = QtWidgets.QLineEdit(self.rightButtons)
        self.user_name.setMinimumSize(QtCore.QSize(100, 50))
        self.user_name.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.user_name.setFont(font)
        self.user_name.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(33, 37, 43);\n"
"border-width:0;border-style:outset")
        self.user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name.setObjectName("user_name")
        self.horizontalLayout_2.addWidget(self.user_name)
        self.user_set = QtWidgets.QPushButton(self.rightButtons)
        self.user_set.setMinimumSize(QtCore.QSize(50, 50))
        self.user_set.setMaximumSize(QtCore.QSize(50, 50))
        self.user_set.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user_set.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/person2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_set.setIcon(icon1)
        self.user_set.setIconSize(QtCore.QSize(36, 36))
        self.user_set.setObjectName("user_set")
        self.horizontalLayout_2.addWidget(self.user_set)
        self.settingsTopBtn = QtWidgets.QPushButton(self.rightButtons)
        self.settingsTopBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.settingsTopBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.settingsTopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsTopBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTopBtn.setIcon(icon2)
        self.settingsTopBtn.setIconSize(QtCore.QSize(32, 32))
        self.settingsTopBtn.setObjectName("settingsTopBtn")
        self.horizontalLayout_2.addWidget(self.settingsTopBtn)
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon3)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(32, 32))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon4)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(32, 32))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon5)
        self.closeAppBtn.setIconSize(QtCore.QSize(26, 26))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.UnderContent = QtWidgets.QFrame(Form)
        self.UnderContent.setGeometry(QtCore.QRect(0, 90, 2041, 1191))
        self.UnderContent.setStyleSheet("QFrame#sideBar{\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QFrame#content{\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"")
        self.UnderContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UnderContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UnderContent.setObjectName("UnderContent")
        self.sideBar = QtWidgets.QFrame(self.UnderContent)
        self.sideBar.setGeometry(QtCore.QRect(0, 0, 120, 1200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideBar.sizePolicy().hasHeightForWidth())
        self.sideBar.setSizePolicy(sizePolicy)
        self.sideBar.setMinimumSize(QtCore.QSize(120, 1200))
        self.sideBar.setMaximumSize(QtCore.QSize(120, 1000))
        self.sideBar.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    min-width: 110px;                            /* 控件最小宽度 */\n"
"    min-height: 90px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-left: 3px outset #714288;  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    background-color:rgb(92, 0, 138);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.sideBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.gridLayout = QtWidgets.QGridLayout(self.sideBar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.monitor = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.monitor.setFont(font)
        self.monitor.setStyleSheet("color: rgb(255, 255, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.monitor.setIcon(icon6)
        self.monitor.setIconSize(QtCore.QSize(27, 27))
        self.monitor.setCheckable(True)
        self.monitor.setAutoExclusive(True)
        self.monitor.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.monitor.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 0, 0, 1, 1)
        self.vio_side = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.vio_side.setFont(font)
        self.vio_side.setStyleSheet("color: rgb(255, 255, 255);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/images/vioDetect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vio_side.setIcon(icon7)
        self.vio_side.setIconSize(QtCore.QSize(30, 30))
        self.vio_side.setCheckable(True)
        self.vio_side.setAutoExclusive(True)
        self.vio_side.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.vio_side.setObjectName("vio_side")
        self.gridLayout.addWidget(self.vio_side, 1, 0, 1, 1)
        self.infoQuery = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.infoQuery.setFont(font)
        self.infoQuery.setStyleSheet("color: rgb(255, 255, 255);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoQuery.setIcon(icon8)
        self.infoQuery.setIconSize(QtCore.QSize(27, 27))
        self.infoQuery.setCheckable(True)
        self.infoQuery.setAutoExclusive(True)
        self.infoQuery.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.infoQuery.setObjectName("infoQuery")
        self.gridLayout.addWidget(self.infoQuery, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.settingUp = QtWidgets.QToolButton(self.sideBar)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.settingUp.setFont(font)
        self.settingUp.setStyleSheet("color: rgb(255, 255, 255);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/aboutUs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingUp.setIcon(icon9)
        self.settingUp.setIconSize(QtCore.QSize(27, 27))
        self.settingUp.setCheckable(True)
        self.settingUp.setAutoExclusive(True)
        self.settingUp.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.settingUp.setObjectName("settingUp")
        self.gridLayout.addWidget(self.settingUp, 4, 0, 1, 1)
        self.content = QtWidgets.QFrame(self.UnderContent)
        self.content.setGeometry(QtCore.QRect(119, -1, 1921, 1200))
        self.content.setMinimumSize(QtCore.QSize(1271, 785))
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 1921, 1191))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setStyleSheet("background-position: center;\n"
"background-image: url(:/images/images/logo.png);\n"
"background-repeat: no-repeat;\n"
"")
        self.Home.setObjectName("Home")
        self.stackedWidget.addWidget(self.Home)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.left_content = QtWidgets.QFrame(self.page_1)
        self.left_content.setGeometry(QtCore.QRect(0, 0, 591, 1191))
        self.left_content.setStyleSheet("background-color: rgb(40, 40, 60);\n"
"background-color: rgb(40, 44, 52);")
        self.left_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_content.setObjectName("left_content")
        self.left_top = QtWidgets.QFrame(self.left_content)
        self.left_top.setGeometry(QtCore.QRect(10, 10, 561, 250))
        self.left_top.setMinimumSize(QtCore.QSize(0, 250))
        self.left_top.setMaximumSize(QtCore.QSize(16777215, 250))
        self.left_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_top.setObjectName("left_top")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_top)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LayOut_liuliang = QtWidgets.QHBoxLayout()
        self.LayOut_liuliang.setSpacing(0)
        self.LayOut_liuliang.setObjectName("LayOut_liuliang")
        self.totalNum = QtWidgets.QFrame(self.left_top)
        self.totalNum.setMinimumSize(QtCore.QSize(200, 145))
        self.totalNum.setMaximumSize(QtCore.QSize(200, 200))
        self.totalNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalNum.setObjectName("totalNum")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.totalNum)
        self.gridLayout_3.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_totalNum = QtWidgets.QLabel(self.totalNum)
        self.label_totalNum.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_totalNum.setFont(font)
        self.label_totalNum.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_totalNum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalNum.setObjectName("label_totalNum")
        self.gridLayout_3.addWidget(self.label_totalNum, 0, 0, 1, 1)
        self.totalUp = QtWidgets.QFrame(self.totalNum)
        self.totalUp.setMinimumSize(QtCore.QSize(100, 30))
        self.totalUp.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.totalUp.setFont(font)
        self.totalUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalUp.setObjectName("totalUp")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.totalUp)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_totalUp = QtWidgets.QLabel(self.totalUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_totalUp.sizePolicy().hasHeightForWidth())
        self.label_totalUp.setSizePolicy(sizePolicy)
        self.label_totalUp.setMinimumSize(QtCore.QSize(100, 30))
        self.label_totalUp.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_totalUp.setFont(font)
        self.label_totalUp.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_totalUp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_totalUp.setObjectName("label_totalUp")
        self.horizontalLayout_6.addWidget(self.label_totalUp)
        self.lineEdit_totalUp = QtWidgets.QLineEdit(self.totalUp)
        self.lineEdit_totalUp.setMinimumSize(QtCore.QSize(70, 30))
        self.lineEdit_totalUp.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_totalUp.setFont(font)
        self.lineEdit_totalUp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_totalUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_totalUp.setObjectName("lineEdit_totalUp")
        self.horizontalLayout_6.addWidget(self.lineEdit_totalUp)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout_3.addWidget(self.totalUp, 3, 0, 1, 1)
        self.totalNumber = QtWidgets.QLineEdit(self.totalNum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalNumber.sizePolicy().hasHeightForWidth())
        self.totalNumber.setSizePolicy(sizePolicy)
        self.totalNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.totalNumber.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.totalNumber.setFont(font)
        self.totalNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.totalNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.totalNumber.setObjectName("totalNumber")
        self.gridLayout_3.addWidget(self.totalNumber, 2, 0, 1, 1)
        self.LayOut_liuliang.addWidget(self.totalNum)
        self.inNum = QtWidgets.QFrame(self.left_top)
        self.inNum.setMinimumSize(QtCore.QSize(200, 145))
        self.inNum.setMaximumSize(QtCore.QSize(200, 200))
        self.inNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inNum.setObjectName("inNum")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.inNum)
        self.gridLayout_5.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_inNum = QtWidgets.QLabel(self.inNum)
        self.label_inNum.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_inNum.setFont(font)
        self.label_inNum.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_inNum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inNum.setObjectName("label_inNum")
        self.gridLayout_5.addWidget(self.label_inNum, 0, 0, 1, 1)
        self.inNumber = QtWidgets.QLineEdit(self.inNum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inNumber.sizePolicy().hasHeightForWidth())
        self.inNumber.setSizePolicy(sizePolicy)
        self.inNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.inNumber.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.inNumber.setFont(font)
        self.inNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.inNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.inNumber.setObjectName("inNumber")
        self.gridLayout_5.addWidget(self.inNumber, 1, 0, 1, 1)
        self.inUp = QtWidgets.QFrame(self.inNum)
        self.inUp.setMinimumSize(QtCore.QSize(100, 30))
        self.inUp.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        self.inUp.setFont(font)
        self.inUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inUp.setObjectName("inUp")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.inUp)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_inUp = QtWidgets.QLabel(self.inUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_inUp.sizePolicy().hasHeightForWidth())
        self.label_inUp.setSizePolicy(sizePolicy)
        self.label_inUp.setMinimumSize(QtCore.QSize(100, 30))
        self.label_inUp.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_inUp.setFont(font)
        self.label_inUp.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_inUp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inUp.setObjectName("label_inUp")
        self.horizontalLayout_13.addWidget(self.label_inUp)
        self.lineEdit_inUp = QtWidgets.QLineEdit(self.inUp)
        self.lineEdit_inUp.setMinimumSize(QtCore.QSize(70, 30))
        self.lineEdit_inUp.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_inUp.setFont(font)
        self.lineEdit_inUp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_inUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_inUp.setObjectName("lineEdit_inUp")
        self.horizontalLayout_13.addWidget(self.lineEdit_inUp)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.gridLayout_5.addWidget(self.inUp, 2, 0, 1, 1)
        self.LayOut_liuliang.addWidget(self.inNum)
        self.outNum = QtWidgets.QFrame(self.left_top)
        self.outNum.setMinimumSize(QtCore.QSize(200, 145))
        self.outNum.setMaximumSize(QtCore.QSize(200, 200))
        self.outNum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outNum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outNum.setObjectName("outNum")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.outNum)
        self.gridLayout_2.setContentsMargins(0, 0, 1, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_outNum = QtWidgets.QLabel(self.outNum)
        self.label_outNum.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_outNum.setFont(font)
        self.label_outNum.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_outNum.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outNum.setObjectName("label_outNum")
        self.gridLayout_2.addWidget(self.label_outNum, 0, 0, 1, 1)
        self.outNumber = QtWidgets.QLineEdit(self.outNum)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outNumber.sizePolicy().hasHeightForWidth())
        self.outNumber.setSizePolicy(sizePolicy)
        self.outNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.outNumber.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.outNumber.setFont(font)
        self.outNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.outNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.outNumber.setObjectName("outNumber")
        self.gridLayout_2.addWidget(self.outNumber, 1, 0, 1, 1)
        self.outUp = QtWidgets.QFrame(self.outNum)
        self.outUp.setMinimumSize(QtCore.QSize(100, 30))
        self.outUp.setMaximumSize(QtCore.QSize(160, 30))
        self.outUp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outUp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outUp.setObjectName("outUp")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.outUp)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_outUp = QtWidgets.QLabel(self.outUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_outUp.sizePolicy().hasHeightForWidth())
        self.label_outUp.setSizePolicy(sizePolicy)
        self.label_outUp.setMinimumSize(QtCore.QSize(100, 30))
        self.label_outUp.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_outUp.setFont(font)
        self.label_outUp.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_outUp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outUp.setObjectName("label_outUp")
        self.horizontalLayout_4.addWidget(self.label_outUp)
        self.lineEdit_outUp = QtWidgets.QLineEdit(self.outUp)
        self.lineEdit_outUp.setMinimumSize(QtCore.QSize(70, 30))
        self.lineEdit_outUp.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_outUp.setFont(font)
        self.lineEdit_outUp.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 44, 52);\n"
"border-width:0;border-style:outset")
        self.lineEdit_outUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_outUp.setObjectName("lineEdit_outUp")
        self.horizontalLayout_4.addWidget(self.lineEdit_outUp)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.outUp, 2, 0, 1, 1)
        self.LayOut_liuliang.addWidget(self.outNum)
        self.verticalLayout.addLayout(self.LayOut_liuliang)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.label_query = QtWidgets.QLabel(self.left_top)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_query.setFont(font)
        self.label_query.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_query.setObjectName("label_query")
        self.verticalLayout.addWidget(self.label_query)
        self.center_content = QtWidgets.QFrame(self.page_1)
        self.center_content.setGeometry(QtCore.QRect(590, 0, 751, 1191))
        self.center_content.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.center_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_content.setObjectName("center_content")
        self.vedio_ori = QtWidgets.QWidget(self.center_content)
        self.vedio_ori.setGeometry(QtCore.QRect(20, 90, 691, 491))
        self.vedio_ori.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_ori.setObjectName("vedio_ori")
        self.vedio_pro = QtWidgets.QWidget(self.center_content)
        self.vedio_pro.setGeometry(QtCore.QRect(20, 610, 691, 491))
        self.vedio_pro.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_pro.setObjectName("vedio_pro")
        self.widget = QtWidgets.QWidget(self.center_content)
        self.widget.setGeometry(QtCore.QRect(20, 1120, 681, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/images/folderOpen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon10)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_5.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/images/bofang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setStyleSheet("/*horizontal ：水平QSlider*/\n"
"QSlider::groove:horizontal {\n"
"border: 0px solid #bbb;\n"
"}\n"
"\n"
"/*1.滑动过的槽设计参数*/\n"
"QSlider::sub-page:horizontal {\n"
" /*槽颜色*/\n"
"background: rgb(90,49,255);\n"
" /*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:8px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:8px;\n"
"/*width在这里无效，不写即可*/\n"
"}\n"
"\n"
"/*2.未滑动过的槽设计参数*/\n"
"QSlider::add-page:horizontal {\n"
"/*槽颜色*/\n"
"background: rgb(255,255, 255);\n"
"/*外环大小0px就是不显示，默认也是0*/\n"
"border: 1px solid #777;\n"
"/*外环区域倒圆角度*/\n"
"border-radius: 2px;\n"
" /*上遮住区域高度*/\n"
"margin-top:9px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:9px;\n"
"}\n"
" \n"
"/*3.平时滑动的滑块设计参数*/\n"
"QSlider::handle:horizontal {\n"
"/*滑块颜色*/\n"
"background: rgb(193,204,208);\n"
"/*滑块的宽度*/\n"
"width: 5px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(193,204,208);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 2px; \n"
" /*上遮住区域高度*/\n"
"margin-top:6px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:6px;\n"
"}\n"
"\n"
"/*4.手动拉动时显示的滑块设计参数*/\n"
"QSlider::handle:horizontal:hover {\n"
"/*滑块颜色*/\n"
"background: rgb(0, 170, 255);\n"
"/*滑块的宽度*/\n"
"width: 10px;\n"
"/*滑块外环为1px，再加颜色*/\n"
"border: 1px solid rgb(0, 170, 255);\n"
" /*滑块外环倒圆角度*/\n"
"border-radius: 5px; \n"
" /*上遮住区域高度*/\n"
"margin-top:4px;\n"
" /*下遮住区域高度*/\n"
"margin-bottom:4px;\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_8.addWidget(self.horizontalSlider)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 5)
        self.label_query_2 = QtWidgets.QLabel(self.center_content)
        self.label_query_2.setGeometry(QtCore.QRect(30, 29, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_query_2.setFont(font)
        self.label_query_2.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_query_2.setObjectName("label_query_2")
        self.right_content = QtWidgets.QFrame(self.page_1)
        self.right_content.setGeometry(QtCore.QRect(1340, 0, 581, 1191))
        self.right_content.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.right_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_content.setObjectName("right_content")
        self.widget1 = QtWidgets.QWidget(self.right_content)
        self.widget1.setGeometry(QtCore.QRect(10, 270, 832, 873))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.label_vio_rt = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_vio_rt.setFont(font)
        self.label_vio_rt.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_vio_rt.setObjectName("label_vio_rt")
        self.horizontalLayout_7.addWidget(self.label_vio_rt)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.scrollArea = QtWidgets.QScrollArea(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(540, 380))
        self.scrollArea.setMaximumSize(QtCore.QSize(540, 380))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {/*设置滚动条背景*/\n"
"    border: none;\n"
"    border-radius:5px;\n"
"    width: 10px;\n"
"    background:rgba(153, 153, 153, 0.5);\n"
"}\n"
"QScrollBar::handle:vertical {/*设置滑动条*/\n"
"    border: none;\n"
"    border-radius:5px; \n"
"    background-color: rgb(55, 156, 212);\n"
"  }\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      height: 0px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      height: 0px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"  QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border:none;\n"
"      width: 0px;\n"
"      height: 0px;\n"
"  }\n"
"  QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
" \n"
" \n"
" \n"
" \n"
"QScrollBar:horizontal {/*设置滚动条背景*/\n"
"    border: none;\n"
"    border-radius:2px;\n"
"    height: 20px;\n"
"    background:rgba(153, 153, 153, 0.5);\n"
"    border-image: url(:/icon/tou.png);\n"
"}\n"
"QScrollBar::handle:horizontal {/*设置滑动条*/\n"
"    border: none;\n"
"    border-radius:2px; \n"
" \n"
"    background-color: rgb(55, 156, 212);\n"
"  }\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: none;\n"
"      width: 0px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"QScrollBar::add-line:horizontal {\n"
"      border: none;\n"
"      width: 0px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"  QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:vertical {\n"
"    border:none;\n"
"      width: 0px;\n"
"      height: 0px;\n"
"  }\n"
"  QScrollBar::add-page:horizontal, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
" \n"
" \n"
" \n"
" \n"
" ")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 530, 566))
        self.scrollAreaWidgetContents.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(500, 540))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(500, 540))
        self.plainTextEdit.setStyleSheet("\n"
"\n"
"            QPlainTextEdit {\n"
"                background-color: rgb(33, 37, 43);\n"
"                color: white;\n"
"                font-size: 12pt;\n"
"                selection-background-color: rgb(92, 0, 138);\n"
"            }\n"
"")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_11.addWidget(self.plainTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem5)
        self.label_vio_rt_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_vio_rt_7.setFont(font)
        self.label_vio_rt_7.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_vio_rt_7.setObjectName("label_vio_rt_7")
        self.horizontalLayout_27.addWidget(self.label_vio_rt_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(540, 380))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(540, 380))
        self.scrollArea_2.setStyleSheet("QScrollBar:vertical {/*设置滚动条背景*/\n"
"    border: none;\n"
"    border-radius:5px;\n"
"    width: 10px;\n"
"    background:rgba(153, 153, 153, 0.5);\n"
"}\n"
"QScrollBar::handle:vertical {/*设置滑动条*/\n"
"    border: none;\n"
"    border-radius:5px; \n"
"    background-color: rgb(55, 156, 212);\n"
"  }\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      height: 0px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      height: 0px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"  QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border:none;\n"
"      width: 0px;\n"
"      height: 0px;\n"
"  }\n"
"  QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
" \n"
" \n"
" \n"
" \n"
"QScrollBar:horizontal {/*设置滚动条背景*/\n"
"    border: none;\n"
"    border-radius:2px;\n"
"    height: 20px;\n"
"    background:rgba(153, 153, 153, 0.5);\n"
"    border-image: url(:/icon/tou.png);\n"
"}\n"
"QScrollBar::handle:horizontal {/*设置滑动条*/\n"
"    border: none;\n"
"    border-radius:2px; \n"
" \n"
"    background-color: rgb(55, 156, 212);\n"
"  }\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: none;\n"
"      width: 0px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"QScrollBar::add-line:horizontal {\n"
"      border: none;\n"
"      width: 0px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"  }\n"
"  QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:vertical {\n"
"    border:none;\n"
"      width: 0px;\n"
"      height: 0px;\n"
"  }\n"
"  QScrollBar::add-page:horizontal, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"  }\n"
" \n"
" \n"
" \n"
" \n"
" ")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 530, 566))
        self.scrollAreaWidgetContents_7.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }")
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_7.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_7.setSizePolicy(sizePolicy)
        self.plainTextEdit_7.setMinimumSize(QtCore.QSize(500, 540))
        self.plainTextEdit_7.setMaximumSize(QtCore.QSize(500, 540))
        self.plainTextEdit_7.setStyleSheet("QPlainTextEdit { background-color: rgb(33, 37, 43); color: white; font-size: 12pt; selection-background-color: rgb(92, 0, 138); }")
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.horizontalLayout_28.addWidget(self.plainTextEdit_7)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.scrollArea.raise_()
        self.scrollArea_2.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.top_bar = QtWidgets.QFrame(self.page_2)
        self.top_bar.setGeometry(QtCore.QRect(0, 0, 1921, 51))
        self.top_bar.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 160px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-bottom: 3px outset rgb(170, 99, 204);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    background-color:rgb(92, 0, 138);    \n"
"}")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.violations = QtWidgets.QToolButton(self.top_bar)
        self.violations.setMinimumSize(QtCore.QSize(166, 46))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.violations.setFont(font)
        self.violations.setStyleSheet("color: rgb(255, 255, 255);")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/images/vehicle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.violations.setIcon(icon12)
        self.violations.setIconSize(QtCore.QSize(26, 26))
        self.violations.setCheckable(True)
        self.violations.setAutoExclusive(True)
        self.violations.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.violations.setObjectName("violations")
        self.horizontalLayout_10.addWidget(self.violations)
        self.flow = QtWidgets.QToolButton(self.top_bar)
        self.flow.setMinimumSize(QtCore.QSize(166, 46))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.flow.setFont(font)
        self.flow.setStyleSheet("color: rgb(255, 255, 255);")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/images/flow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flow.setIcon(icon13)
        self.flow.setIconSize(QtCore.QSize(26, 26))
        self.flow.setCheckable(True)
        self.flow.setAutoExclusive(True)
        self.flow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.flow.setObjectName("flow")
        self.horizontalLayout_10.addWidget(self.flow)
        self.blank_2 = QtWidgets.QToolButton(self.top_bar)
        self.blank_2.setMinimumSize(QtCore.QSize(1006, 46))
        self.blank_2.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 1000px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"r")
        self.blank_2.setText("")
        self.blank_2.setObjectName("blank_2")
        self.horizontalLayout_10.addWidget(self.blank_2)
        self.blank = QtWidgets.QToolButton(self.top_bar)
        self.blank.setMinimumSize(QtCore.QSize(1006, 46))
        self.blank.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 1000px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"r")
        self.blank.setText("")
        self.blank.setObjectName("blank")
        self.horizontalLayout_10.addWidget(self.blank)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(3, 100)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 50, 1921, 1141))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.home_sub = QtWidgets.QWidget()
        self.home_sub.setStyleSheet("")
        self.home_sub.setObjectName("home_sub")
        self.label = QtWidgets.QLabel(self.home_sub)
        self.label.setGeometry(QtCore.QRect(550, 310, 741, 501))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/query2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.stackedWidget_2.addWidget(self.home_sub)
        self.info_query = QtWidgets.QWidget()
        self.info_query.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.info_query.setObjectName("info_query")
        self.frame_query = QtWidgets.QFrame(self.info_query)
        self.frame_query.setGeometry(QtCore.QRect(0, 0, 1071, 1141))
        self.frame_query.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_query.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_query.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_query.setObjectName("frame_query")
        self.violation_query = QtWidgets.QFrame(self.frame_query)
        self.violation_query.setGeometry(QtCore.QRect(10, 20, 900, 141))
        self.violation_query.setMinimumSize(QtCore.QSize(700, 0))
        self.violation_query.setMaximumSize(QtCore.QSize(900, 16777215))
        self.violation_query.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.violation_query.setFrameShadow(QtWidgets.QFrame.Raised)
        self.violation_query.setObjectName("violation_query")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.violation_query)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_car_num = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_car_num.setFont(font)
        self.label_car_num.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_car_num.setAlignment(QtCore.Qt.AlignCenter)
        self.label_car_num.setObjectName("label_car_num")
        self.horizontalLayout_5.addWidget(self.label_car_num)
        self.lineEdit_violation = QtWidgets.QLineEdit(self.violation_query)
        self.lineEdit_violation.setMinimumSize(QtCore.QSize(150, 35))
        self.lineEdit_violation.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.lineEdit_violation.setFont(font)
        self.lineEdit_violation.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}")
        self.lineEdit_violation.setObjectName("lineEdit_violation")
        self.horizontalLayout_5.addWidget(self.lineEdit_violation)
        spacerItem6 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_violation = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_violation.setFont(font)
        self.label_violation.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_violation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_violation.setObjectName("label_violation")
        self.horizontalLayout_5.addWidget(self.label_violation)
        self.lineEdit = QtWidgets.QLineEdit(self.violation_query)
        self.lineEdit.setMinimumSize(QtCore.QSize(120, 35))
        self.lineEdit.setMaximumSize(QtCore.QSize(120, 35))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rt_query_end_3 = QtWidgets.QVBoxLayout()
        self.rt_query_end_3.setSpacing(0)
        self.rt_query_end_3.setObjectName("rt_query_end_3")
        self.rt_end_3 = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.rt_end_3.setFont(font)
        self.rt_end_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end_3.setObjectName("rt_end_3")
        self.rt_query_end_3.addWidget(self.rt_end_3)
        spacerItem8 = QtWidgets.QSpacerItem(1, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_end_3.addItem(spacerItem8)
        self.time_start_3 = QtWidgets.QDateTimeEdit(self.violation_query)
        self.time_start_3.setMinimumSize(QtCore.QSize(180, 30))
        self.time_start_3.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.time_start_3.setFont(font)
        self.time_start_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_start_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_start_3.setObjectName("time_start_3")
        self.rt_query_end_3.addWidget(self.time_start_3)
        self.horizontalLayout_14.addLayout(self.rt_query_end_3)
        spacerItem9 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.rt_query_end_2 = QtWidgets.QVBoxLayout()
        self.rt_query_end_2.setSpacing(0)
        self.rt_query_end_2.setObjectName("rt_query_end_2")
        self.rt_end_2 = QtWidgets.QLabel(self.violation_query)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.rt_end_2.setFont(font)
        self.rt_end_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end_2.setObjectName("rt_end_2")
        self.rt_query_end_2.addWidget(self.rt_end_2)
        spacerItem10 = QtWidgets.QSpacerItem(1, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_end_2.addItem(spacerItem10)
        self.time_end_2 = QtWidgets.QDateTimeEdit(self.violation_query)
        self.time_end_2.setMinimumSize(QtCore.QSize(180, 30))
        self.time_end_2.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.time_end_2.setFont(font)
        self.time_end_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_end_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_end_2.setObjectName("time_end_2")
        self.rt_query_end_2.addWidget(self.time_end_2)
        self.horizontalLayout_14.addLayout(self.rt_query_end_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.pBtn_vio_query = QtWidgets.QPushButton(self.violation_query)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_vio_query.sizePolicy().hasHeightForWidth())
        self.pBtn_vio_query.setSizePolicy(sizePolicy)
        self.pBtn_vio_query.setMinimumSize(QtCore.QSize(100, 40))
        self.pBtn_vio_query.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pBtn_vio_query.setFont(font)
        self.pBtn_vio_query.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/images/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtn_vio_query.setIcon(icon14)
        self.pBtn_vio_query.setObjectName("pBtn_vio_query")
        self.horizontalLayout_15.addWidget(self.pBtn_vio_query)
        self.output_vio = QtWidgets.QPushButton(self.violation_query)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_vio.sizePolicy().hasHeightForWidth())
        self.output_vio.setSizePolicy(sizePolicy)
        self.output_vio.setMinimumSize(QtCore.QSize(150, 40))
        self.output_vio.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.output_vio.setFont(font)
        self.output_vio.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/images/output_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.output_vio.setIcon(icon15)
        self.output_vio.setIconSize(QtCore.QSize(22, 22))
        self.output_vio.setObjectName("output_vio")
        self.horizontalLayout_15.addWidget(self.output_vio)
        self.frame_statistics = QtWidgets.QFrame(self.info_query)
        self.frame_statistics.setGeometry(QtCore.QRect(1075, 0, 851, 1141))
        self.frame_statistics.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_statistics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_statistics.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_statistics.setObjectName("frame_statistics")
        self.pBtn_vio_statistics = QtWidgets.QPushButton(self.frame_statistics)
        self.pBtn_vio_statistics.setGeometry(QtCore.QRect(80, 20, 191, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_vio_statistics.sizePolicy().hasHeightForWidth())
        self.pBtn_vio_statistics.setSizePolicy(sizePolicy)
        self.pBtn_vio_statistics.setMinimumSize(QtCore.QSize(150, 45))
        self.pBtn_vio_statistics.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pBtn_vio_statistics.setFont(font)
        self.pBtn_vio_statistics.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/images/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pBtn_vio_statistics.setIcon(icon16)
        self.pBtn_vio_statistics.setIconSize(QtCore.QSize(28, 28))
        self.pBtn_vio_statistics.setObjectName("pBtn_vio_statistics")
        self.widget_vio_statistics = QtWidgets.QWidget(self.frame_statistics)
        self.widget_vio_statistics.setGeometry(QtCore.QRect(60, 90, 731, 1011))
        self.widget_vio_statistics.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"border-top-right-radius: 8px;         /* 右上角圆角 */\n"
"border-top-left-radius: 8px;        \n"
"border-bottom-right-radius: 8px;      /* 右下角圆角 */\n"
"border-bottom-left-radius: 8px;         /* 右上角圆角 */")
        self.widget_vio_statistics.setObjectName("widget_vio_statistics")
        self.stackedWidget_2.addWidget(self.info_query)
        self.info_query_flow = QtWidgets.QWidget()
        self.info_query_flow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.info_query_flow.setObjectName("info_query_flow")
        self.frame_query_flow = QtWidgets.QFrame(self.info_query_flow)
        self.frame_query_flow.setGeometry(QtCore.QRect(0, 0, 1071, 1141))
        self.frame_query_flow.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_query_flow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_query_flow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_query_flow.setObjectName("frame_query_flow")
        self.flow_query = QtWidgets.QFrame(self.frame_query_flow)
        self.flow_query.setGeometry(QtCore.QRect(10, 20, 750, 141))
        self.flow_query.setMinimumSize(QtCore.QSize(750, 0))
        self.flow_query.setMaximumSize(QtCore.QSize(750, 16777215))
        self.flow_query.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.flow_query.setFrameShadow(QtWidgets.QFrame.Raised)
        self.flow_query.setObjectName("flow_query")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.flow_query)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_violation_2 = QtWidgets.QLabel(self.flow_query)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_violation_2.setFont(font)
        self.label_violation_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_violation_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_violation_2.setObjectName("label_violation_2")
        self.horizontalLayout_17.addWidget(self.label_violation_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.flow_query)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(150, 35))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(150, 35))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_17.addWidget(self.lineEdit_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.rt_query_end_5 = QtWidgets.QVBoxLayout()
        self.rt_query_end_5.setSpacing(0)
        self.rt_query_end_5.setObjectName("rt_query_end_5")
        self.rt_end_5 = QtWidgets.QLabel(self.flow_query)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.rt_end_5.setFont(font)
        self.rt_end_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end_5.setObjectName("rt_end_5")
        self.rt_query_end_5.addWidget(self.rt_end_5)
        spacerItem13 = QtWidgets.QSpacerItem(1, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_end_5.addItem(spacerItem13)
        self.time_start_5 = QtWidgets.QDateTimeEdit(self.flow_query)
        self.time_start_5.setMinimumSize(QtCore.QSize(180, 30))
        self.time_start_5.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.time_start_5.setFont(font)
        self.time_start_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_start_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_start_5.setObjectName("time_start_5")
        self.rt_query_end_5.addWidget(self.time_start_5)
        self.horizontalLayout_19.addLayout(self.rt_query_end_5)
        spacerItem14 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem15)
        self.rt_query_end_4 = QtWidgets.QVBoxLayout()
        self.rt_query_end_4.setSpacing(0)
        self.rt_query_end_4.setObjectName("rt_query_end_4")
        self.rt_end_4 = QtWidgets.QLabel(self.flow_query)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.rt_end_4.setFont(font)
        self.rt_end_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.rt_end_4.setObjectName("rt_end_4")
        self.rt_query_end_4.addWidget(self.rt_end_4)
        spacerItem16 = QtWidgets.QSpacerItem(1, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.rt_query_end_4.addItem(spacerItem16)
        self.time_end_4 = QtWidgets.QDateTimeEdit(self.flow_query)
        self.time_end_4.setMinimumSize(QtCore.QSize(180, 30))
        self.time_end_4.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.time_end_4.setFont(font)
        self.time_end_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_end_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-width: 1px")
        self.time_end_4.setObjectName("time_end_4")
        self.rt_query_end_4.addWidget(self.time_end_4)
        self.horizontalLayout_19.addLayout(self.rt_query_end_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16.addLayout(self.verticalLayout_4)
        self.pBtn_vio_query_2 = QtWidgets.QPushButton(self.flow_query)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_vio_query_2.sizePolicy().hasHeightForWidth())
        self.pBtn_vio_query_2.setSizePolicy(sizePolicy)
        self.pBtn_vio_query_2.setMinimumSize(QtCore.QSize(100, 40))
        self.pBtn_vio_query_2.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pBtn_vio_query_2.setFont(font)
        self.pBtn_vio_query_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.pBtn_vio_query_2.setIcon(icon14)
        self.pBtn_vio_query_2.setObjectName("pBtn_vio_query_2")
        self.horizontalLayout_16.addWidget(self.pBtn_vio_query_2)
        self.output_vio_2 = QtWidgets.QPushButton(self.flow_query)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_vio_2.sizePolicy().hasHeightForWidth())
        self.output_vio_2.setSizePolicy(sizePolicy)
        self.output_vio_2.setMinimumSize(QtCore.QSize(150, 40))
        self.output_vio_2.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.output_vio_2.setFont(font)
        self.output_vio_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.output_vio_2.setIcon(icon15)
        self.output_vio_2.setIconSize(QtCore.QSize(22, 22))
        self.output_vio_2.setObjectName("output_vio_2")
        self.horizontalLayout_16.addWidget(self.output_vio_2)
        self.frame_statistics_flow = QtWidgets.QFrame(self.info_query_flow)
        self.frame_statistics_flow.setGeometry(QtCore.QRect(1075, 0, 851, 1141))
        self.frame_statistics_flow.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_statistics_flow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_statistics_flow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_statistics_flow.setObjectName("frame_statistics_flow")
        self.widget_flow_statistics = QtWidgets.QWidget(self.frame_statistics_flow)
        self.widget_flow_statistics.setGeometry(QtCore.QRect(60, 90, 731, 1011))
        self.widget_flow_statistics.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"border-top-right-radius: 8px;         /* 右上角圆角 */\n"
"border-top-left-radius: 8px;        \n"
"border-bottom-right-radius: 8px;      /* 右下角圆角 */\n"
"border-bottom-left-radius: 8px;         /* 右上角圆角 */")
        self.widget_flow_statistics.setObjectName("widget_flow_statistics")
        self.pBtn_flow_statistics = QtWidgets.QPushButton(self.frame_statistics_flow)
        self.pBtn_flow_statistics.setGeometry(QtCore.QRect(80, 20, 191, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBtn_flow_statistics.sizePolicy().hasHeightForWidth())
        self.pBtn_flow_statistics.setSizePolicy(sizePolicy)
        self.pBtn_flow_statistics.setMinimumSize(QtCore.QSize(150, 45))
        self.pBtn_flow_statistics.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pBtn_flow_statistics.setFont(font)
        self.pBtn_flow_statistics.setStyleSheet("QPushButton{\n"
"    background-color: rgb(40, 44, 52);\n"
"    border-radius: 5px;\n"
"    border: 2px solid #404758;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QPushButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QPushButton:pressed,QToolButton:checked{\n"
"    background-color:rgb(33, 37, 43);    \n"
"}\n"
"\n"
"/* QPushButton:default {\n"
"    border-color: navy; \n"
"} */\n"
"")
        self.pBtn_flow_statistics.setIcon(icon16)
        self.pBtn_flow_statistics.setIconSize(QtCore.QSize(28, 28))
        self.pBtn_flow_statistics.setObjectName("pBtn_flow_statistics")
        self.stackedWidget_2.addWidget(self.info_query_flow)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.vio = QtWidgets.QWidget()
        self.vio.setObjectName("vio")
        self.top_bar_vio = QtWidgets.QFrame(self.vio)
        self.top_bar_vio.setGeometry(QtCore.QRect(0, 0, 1921, 51))
        self.top_bar_vio.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 200px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"\n"
"/* 鼠标悬停 */\n"
"QToolButton:hover{\n"
"    background-color: rgb(205, 205, 205);\n"
"}\n"
"\n"
"/* 点击和按下 */\n"
"QToolButton:pressed,QToolButton:checked{\n"
"    border-bottom: 3px outset rgb(170, 99, 204);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    background-color:rgb(92, 0, 138);    \n"
"}")
        self.top_bar_vio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar_vio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar_vio.setObjectName("top_bar_vio")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.top_bar_vio)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.red_car = QtWidgets.QToolButton(self.top_bar_vio)
        self.red_car.setMinimumSize(QtCore.QSize(206, 46))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.red_car.setFont(font)
        self.red_car.setStyleSheet("color: rgb(255, 255, 255);")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/images/car_vio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.red_car.setIcon(icon17)
        self.red_car.setIconSize(QtCore.QSize(32, 32))
        self.red_car.setCheckable(True)
        self.red_car.setAutoExclusive(True)
        self.red_car.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.red_car.setObjectName("red_car")
        self.horizontalLayout_18.addWidget(self.red_car)
        self.red_person = QtWidgets.QToolButton(self.top_bar_vio)
        self.red_person.setMinimumSize(QtCore.QSize(206, 46))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.red_person.setFont(font)
        self.red_person.setStyleSheet("color: rgb(255, 255, 255);")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/images/person_vio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.red_person.setIcon(icon18)
        self.red_person.setIconSize(QtCore.QSize(32, 32))
        self.red_person.setCheckable(True)
        self.red_person.setAutoExclusive(True)
        self.red_person.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.red_person.setObjectName("red_person")
        self.horizontalLayout_18.addWidget(self.red_person)
        self.blank_7 = QtWidgets.QToolButton(self.top_bar_vio)
        self.blank_7.setMinimumSize(QtCore.QSize(1006, 46))
        self.blank_7.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 1000px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"r")
        self.blank_7.setText("")
        self.blank_7.setObjectName("blank_7")
        self.horizontalLayout_18.addWidget(self.blank_7)
        self.blank_8 = QtWidgets.QToolButton(self.top_bar_vio)
        self.blank_8.setMinimumSize(QtCore.QSize(1006, 46))
        self.blank_8.setStyleSheet("/* 默认 */\n"
"\n"
"QToolButton{   \n"
"    border-top: 3px outset transparent;           /* 上边框宽度3像素、突出显示、颜色为透明 */\n"
"    border-bottom: 7px outset transparent;\n"
"    border-right: 3px outset transparent;\n"
"    border-left: 3px outset transparent;\n"
"    border-bottom: 3px outset rgb(255, 255, 255);  /* 左边框宽度3像素、突出显示、颜色为深深灰 */\n"
"    min-width: 1000px;                            /* 控件最小宽度 */\n"
"    min-height: 40px;\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"r")
        self.blank_8.setText("")
        self.blank_8.setObjectName("blank_8")
        self.horizontalLayout_18.addWidget(self.blank_8)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.setStretch(3, 100)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.vio)
        self.stackedWidget_3.setGeometry(QtCore.QRect(0, 50, 1921, 1141))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.car_widget = QtWidgets.QWidget()
        self.car_widget.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.car_widget.setObjectName("car_widget")
        self.vedio_pro_car = QtWidgets.QWidget(self.car_widget)
        self.vedio_pro_car.setGeometry(QtCore.QRect(1000, 160, 840, 600))
        self.vedio_pro_car.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_pro_car.setObjectName("vedio_pro_car")
        self.vedio_ori_car = QtWidgets.QWidget(self.car_widget)
        self.vedio_ori_car.setGeometry(QtCore.QRect(80, 160, 840, 600))
        self.vedio_ori_car.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_ori_car.setObjectName("vedio_ori_car")
        self.label_car = QtWidgets.QLabel(self.car_widget)
        self.label_car.setGeometry(QtCore.QRect(120, 60, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_car.setFont(font)
        self.label_car.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_car.setObjectName("label_car")
        self.car_con = QtWidgets.QPushButton(self.car_widget)
        self.car_con.setGeometry(QtCore.QRect(80, 800, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_con.sizePolicy().hasHeightForWidth())
        self.car_con.setSizePolicy(sizePolicy)
        self.car_con.setMinimumSize(QtCore.QSize(30, 30))
        self.car_con.setText("")
        self.car_con.setIcon(icon11)
        self.car_con.setIconSize(QtCore.QSize(48, 48))
        self.car_con.setObjectName("car_con")
        self.stackedWidget_3.addWidget(self.car_widget)
        self.person_widget = QtWidgets.QWidget()
        self.person_widget.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.person_widget.setObjectName("person_widget")
        self.vedio_ori_person = QtWidgets.QWidget(self.person_widget)
        self.vedio_ori_person.setGeometry(QtCore.QRect(80, 160, 840, 600))
        self.vedio_ori_person.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_ori_person.setObjectName("vedio_ori_person")
        self.vedio_pro_person = QtWidgets.QWidget(self.person_widget)
        self.vedio_pro_person.setGeometry(QtCore.QRect(1000, 160, 840, 600))
        self.vedio_pro_person.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vedio_pro_person.setObjectName("vedio_pro_person")
        self.label_car_2 = QtWidgets.QLabel(self.person_widget)
        self.label_car_2.setGeometry(QtCore.QRect(120, 60, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_car_2.setFont(font)
        self.label_car_2.setStyleSheet("color: rgb(0, 170, 255);\n"
"")
        self.label_car_2.setObjectName("label_car_2")
        self.person_con = QtWidgets.QPushButton(self.person_widget)
        self.person_con.setGeometry(QtCore.QRect(80, 800, 71, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.person_con.sizePolicy().hasHeightForWidth())
        self.person_con.setSizePolicy(sizePolicy)
        self.person_con.setMinimumSize(QtCore.QSize(30, 30))
        self.person_con.setText("")
        self.person_con.setIcon(icon11)
        self.person_con.setIconSize(QtCore.QSize(48, 48))
        self.person_con.setObjectName("person_con")
        self.stackedWidget_3.addWidget(self.person_widget)
        self.stackedWidget.addWidget(self.vio)
        self.content.raise_()
        self.sideBar.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(4)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleRightInfo.setText(_translate("Form", "Intelligent Traffic Management System"))
        self.user_name.setText(_translate("Form", "用户名"))
        self.user_set.setToolTip(_translate("Form", "Settings"))
        self.settingsTopBtn.setToolTip(_translate("Form", "Settings"))
        self.minimizeAppBtn.setToolTip(_translate("Form", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("Form", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("Form", "Close"))
        self.monitor.setText(_translate("Form", "实时监控"))
        self.vio_side.setText(_translate("Form", "违规检测"))
        self.infoQuery.setText(_translate("Form", "信息查询"))
        self.settingUp.setText(_translate("Form", "关于我们"))
        self.label_totalNum.setText(_translate("Form", " 现车流总数"))
        self.label_totalUp.setText(_translate("Form", "同比增长 "))
        self.lineEdit_totalUp.setText(_translate("Form", "00.0%"))
        self.totalNumber.setText(_translate("Form", "0"))
        self.label_inNum.setText(_translate("Form", "驶入总数"))
        self.inNumber.setText(_translate("Form", "0"))
        self.label_inUp.setText(_translate("Form", "同比增长 "))
        self.lineEdit_inUp.setText(_translate("Form", "00.0%"))
        self.label_outNum.setText(_translate("Form", "驶出总数"))
        self.outNumber.setText(_translate("Form", "0"))
        self.label_outUp.setText(_translate("Form", "同比增长 "))
        self.lineEdit_outUp.setText(_translate("Form", "00.0%"))
        self.label_query.setText(_translate("Form", "   实时车辆信息"))
        self.pushButton_3.setText(_translate("Form", "打开"))
        self.label_query_2.setText(_translate("Form", "视频监控"))
        self.label_vio_rt.setText(_translate("Form", "流量信息实时显示"))
        self.label_vio_rt_7.setText(_translate("Form", "交通疏导策略提示"))
        self.violations.setText(_translate("Form", "车辆查询"))
        self.flow.setText(_translate("Form", " 流量查询"))
        self.label_car_num.setText(_translate("Form", "车牌号"))
        self.label_violation.setText(_translate("Form", "道路序号"))
        self.rt_end_3.setText(_translate("Form", "开始时间："))
        self.rt_end_2.setText(_translate("Form", "终止时间："))
        self.pBtn_vio_query.setText(_translate("Form", "查询"))
        self.output_vio.setText(_translate("Form", "导出数据"))
        self.pBtn_vio_statistics.setText(_translate("Form", "车辆数据分析"))
        self.label_violation_2.setText(_translate("Form", "道路序号"))
        self.rt_end_5.setText(_translate("Form", "开始时间："))
        self.rt_end_4.setText(_translate("Form", "终止时间："))
        self.pBtn_vio_query_2.setText(_translate("Form", "查询"))
        self.output_vio_2.setText(_translate("Form", "导出数据"))
        self.pBtn_flow_statistics.setText(_translate("Form", "流量数据分析"))
        self.red_car.setText(_translate("Form", "车辆闯红灯"))
        self.red_person.setText(_translate("Form", "行人闯红灯"))
        self.label_car.setText(_translate("Form", "车辆闯红灯检测"))
        self.label_car_2.setText(_translate("Form", "行人闯红灯检测"))
